pipeline:
  name: todd pr test
  identifier: todd_pr_test
  projectIdentifier: Tensorflow
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: component a
        identifier: component_a
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: todd_component_a_pr
          project: Tensorflow
          inputSetReferences:
            - componentainputset
          outputs: []
        tags: {}
