# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
mode: parallel
stages:
  - "plan"
  - "fanout"
  - "report"

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: carsongee/tensorflow
    revision: ${{CF_BRANCH}}
    git: github-cg
    stage: plan


  # TODO: Generate pipelines to run
  run_component_a:
    title: Run component A
    image: codefresh/cli
    stage: fanout
    working_directory: ${{clone}}
    commands:
      - codefresh run -y componentA/.cicd/codefresh.yml --pack-name large
    when:
      steps:
        - name: clone
          on:
            - success
  run_component_b:
    title: Run component B
    image: codefresh/cli
    stage: fanout
    working_directory: ${{clone}}
    commands:
      - codefresh run -y componentB/.cicd/codefresh.yml --pack-name large
    when:
      steps:
        - name: clone
          on:
            - success

  evaluate_pipelines:
    image: alpine:latest
    title: Checking pipelines worked
    stage: "report"
    commands:
      - echo "Success!"
    when:
      steps:
        - name: run_component_a
          on:
            - success
        - name: run_component_b
          on:
            - success
