# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "plan"
  - "fanout"
  - "report"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "carsongee/tensorflow"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-cg"
    stage: "plan"

  # TODO: Make dynamic/custom step (or not...nesting is a thing...ask)
  create_component_pipeline_a:
    title: "Make ComponentA pipeline"
    type: pipeline-trigger-merge
    stage: "plan"
    arguments:
      SPEC: componentA/.cicd/codefresh.yml
      TRIGGERS: componentA/.cicd/trigger.yml
  create_component_pipeline_b:
    title: "Make ComponentB pipeline"
    type: pipeline-trigger-merge
    stage: "plan"
    arguments:
      SPEC: componentB/.cicd/codefresh.yml
      TRIGGERS: componentB/.cicd/trigger.yml
  # TODO: Generate pipelines to run
  run_cf_pipelines:
    title: Start pipelines and wait
    type: codefresh-run-dynamic
    stage: fanout
    arguments:
      RUN_LIST_YAML_FILE: .cicd/pipelines.yml
      WAIT: true

  evaluate_pipelines:
    image: alpine:latest
    title: Checking pipelines worked
    stage: "report"
    commands:
      - echo "Success!"
