# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "fanout"
  - "report"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "carsongee/tensorflow"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-cg"
    stage: "clone"

  run_components:
    title: Build and Run Component Pipelines
    type: datarobot/cg-components
    stage: "fanout"
    arguments:
      components:
        - componentA
        - componentB
      yaml_destination: ${{CF_VOLUME_PATH}}/pipelines.yaml
      project: tensorflow
      DEBUG: true

  evaluate_pipelines:
    image: alpine:latest
    title: Checking pipelines worked
    stage: "report"
    commands:
      - echo "Success!"
