# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "carsongee/tensorflow"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-cg"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "carsongee/tensorflow/component"
    working_directory: "${{clone}}/component"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running Tests"
    stage: "test"
    image: "${{build}}" # The image in which command will be executed
    commands:
      - "pytest"
