pipeline:
  name: PR
  identifier: PR
  projectIdentifier: Tensorflow
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test webhook
        identifier: Test_webhook
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo '<+secrets.getValue("account.slackwebhook")>' > /tmp/file.txt
                      cat /tmp/file.txt

                      curl -H "Content-type: application/json" \
                      --data '{"test":"Hello World"}' \
                      -X POST <+secrets.getValue("account.slackwebhook")>
  notificationRules:
    - name: slack-firehose
      identifier: slackfirehose
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: PipelinePaused
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+secrets.getValue("slackwebhook")>
      enabled: true
