pipeline:
  name: PR
  identifier: PR
  projectIdentifier: Tensorflow
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: ComponentA
            identifier: ComponentA
            description: ""
            type: Pipeline
            spec:
              org: default
              pipeline: ComponentAPR
              project: Tensorflow
              inputSetReferences:
                - pr_input_set
              outputs: []
        - stage:
            name: ComponentB
            identifier: ComponentB
            description: ""
            type: Pipeline
            spec:
              org: default
              pipeline: ComponentBPR
              project: Tensorflow
              inputSetReferences:
                - pr_input_set
              outputs: []
  notificationRules:
    - name: slack-firehose
      identifier: slackfirehose
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: PipelinePaused
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
